(add-to-list 'load-path (emacswiki-path "color-theme-6.6.0"))
(add-to-list 'load-path (concat (emacswiki-path "color-theme-6.6.0") "/themes"))
(require 'color-theme)
;;(require 'zenburn)
;;(zenburn)
(require 'color-theme-blackboard)
(color-theme-blackboard)
