(global-set-key (kbd "C-;") 'anything-at-point)
(global-set-key "\M-n"      'duplicate-line)
(global-set-key "\C-x\\"    'align-regexp)
(global-set-key "\M-#"      'comment-or-uncomment-region)
(global-set-key "\C-xp"     'other-window-backward)
(global-set-key (kbd "M-.") 'anything-yaetags-find-tag)